"""``pte generate-overrides <ticker>`` — skeleton ``overrides.yaml``.

Scans the latest :class:`CanonicalCompanyState` for a ticker, finds
every Module D sub-item that needs operator attention, and writes a
template at ``{portfolio_dir}/<ticker>/overrides.yaml.template``.

Items that end up in the template:

- ``action=flag_for_review`` — no regex matched either dimension.
- ``confidence=low`` — the match was weak.
- ``method=label_fallback`` — we couldn't find the source note table;
  the label was classified on its own.

The analyst reviews the template, fills in classifications + a one-
line rationale per item, and renames to ``overrides.yaml`` to
activate.
"""

from __future__ import annotations

from pathlib import Path

import typer
import yaml
from rich.console import Console

from portfolio_thesis_engine.extraction.module_d_overrides import (
    overrides_path_for,
)
from portfolio_thesis_engine.schemas.decomposition import SubItem
from portfolio_thesis_engine.shared.config import settings
from portfolio_thesis_engine.storage.yaml_repo import CompanyStateRepository

console = Console()


def _candidates_from_state(state: object) -> list[tuple[str, SubItem]]:
    """Return ``[(parent_key, SubItem), ...]`` for items needing review."""
    out: list[tuple[str, SubItem]] = []
    adjustments = getattr(state, "adjustments", None)
    decomps = (
        getattr(adjustments, "module_d_note_decompositions", {}) or {}
        if adjustments is not None
        else {}
    )
    for key, decomp in decomps.items():
        for sub in decomp.sub_items:
            needs = (
                sub.action == "flag_for_review"
                or sub.confidence == "low"
                or decomp.method == "label_fallback"
            )
            if needs:
                out.append((key, sub))
    return out


def _render_template(candidates: list[tuple[str, SubItem]], ticker: str) -> str:
    header = (
        "# Phase 1.5.10 — Module D overrides template\n"
        f"# Ticker: {ticker}\n"
        "# Generated by `pte generate-overrides`.\n"
        "#\n"
        "# 1. Review each entry below.\n"
        "# 2. Replace `operational` / `recurring` with one of:\n"
        "#      operational | non_operational | ambiguous\n"
        "#      recurring   | non_recurring   | ambiguous\n"
        "#    Leave a dimension out to fall through to the regex classifier.\n"
        "# 3. Write a one-line `rationale` for the audit trail.\n"
        "# 4. Remove entries you don't want to override (regex default wins).\n"
        "# 5. Rename this file to `overrides.yaml` to activate.\n"
        "\n"
        "version: 1\n"
        "sub_item_classifications:\n"
    )
    if not candidates:
        return (
            header
            + "  # No flagged items — Module D classified everything confidently.\n"
            + "  []\n"
        )
    body_lines: list[str] = []
    for key, sub in candidates:
        body_lines.extend(
            [
                f"  # Parent: {key}",
                f"  # Value:  {sub.value}",
                f"  # Action today: {sub.action} (confidence: {sub.confidence})",
                f"  # Rule matched: {sub.matched_rule}",
                f"  - label_pattern: {yaml.safe_dump(sub.label).strip()}",
                f"    operational: {sub.operational_classification}  # CHANGE ME",
                f"    recurring: {sub.recurrence_classification}     # CHANGE ME",
                "    rationale: REPLACE WITH ONE-LINE AUDIT NOTE",
                "",
            ]
        )
    return header + "\n".join(body_lines)


def generate_overrides(
    ticker: str = typer.Argument(..., help="Ticker to generate overrides for."),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="Optional custom output path. Defaults to "
        "{portfolio_dir}/<ticker>/overrides.yaml.template.",
    ),
) -> None:
    """Emit a user-editable overrides template for Module D."""
    repo = CompanyStateRepository(base_path=settings.data_dir / "states")
    state = repo.load_latest(ticker)
    if state is None:
        console.print(
            f"[red]No canonical state for {ticker}.[/red] Run "
            f"`pte process {ticker}` first."
        )
        raise typer.Exit(code=1)

    candidates = _candidates_from_state(state)
    template = _render_template(candidates, ticker)

    out_path = output or overrides_path_for(ticker).with_suffix(
        ".yaml.template"
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(template, encoding="utf-8")

    console.print(
        f"[green]Wrote {out_path}[/green]\n"
        f"  {len(candidates)} sub-item(s) flagged for review.\n"
        f"  Edit the file and rename to [bold]overrides.yaml[/bold] to activate."
    )


__all__ = ["generate_overrides"]
