/**
 * Hand-rolled fixtures matching the on-the-wire shapes. Keep them
 * compact — the goal is component coverage, not full payload realism.
 */

import type { TickerDetail, TickerSummary, YamlListItem } from "@/lib/types/api";
import type {
  CanonicalState,
  CompanyIdentity,
  ReclassifiedStatements,
} from "@/lib/types/canonical";
import type { Ficha } from "@/lib/types/ficha";
import type { ValuationSnapshot } from "@/lib/types/valuation";

export const tickerSummaryFixture: TickerSummary = {
  ticker: "1846.HK",
  name: "EuroEyes International Eye Clinic Limited",
  profile: "P1",
  currency: "HKD",
  exchange: "HKEX",
  isin: null,
  has_extraction: true,
  has_valuation: true,
  has_forecast: true,
  has_ficha: true,
  latest_extraction_at: "2026-04-24T21:16:44Z",
  latest_valuation_at: "2026-04-24T21:16:44Z",
  latest_forecast_at: "2026-04-24T14:20:15Z",
};

export const tickerDetailFixture: TickerDetail = {
  ticker: "1846.HK",
  name: "EuroEyes International Eye Clinic Limited",
  profile: "P1",
  currency: "HKD",
  exchange: "HKEX",
  isin: null,
  extraction_path: null,
  valuation_path: null,
  forecast_path: null,
  ficha_path: null,
};

export const identityFixture: CompanyIdentity = {
  ticker: "1846.HK",
  isin: null,
  name: "EuroEyes International Eye Clinic Limited",
  legal_name: null,
  reporting_currency: "HKD",
  profile: "P1",
  sector_gics: "Healthcare",
  industry_gics: null,
  fiscal_year_end_month: 12,
  country_domicile: "HK",
  exchange: "HKEX",
  shares_outstanding: "331885000",
  market_contexts: [],
};

const statementYear2024: ReclassifiedStatements = {
  period: { year: 2024, quarter: null, label: "FY2024" },
  income_statement: [
    { label: "Revenue", value: "715682000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Cost of sales", value: "-429089000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Gross profit", value: "286593000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Operating profit", value: "115778000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Profit for the year", value: "84500000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  balance_sheet: [
    { label: "Property, plant and equipment", value: "567413000", is_adjusted: false, adjustment_note: null, source: null, category: "non_current_assets" },
    { label: "Total assets", value: "3700000000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  cash_flow: [
    { label: "Net cash from operating activities", value: "145000000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  bs_checksum_pass: true,
  is_checksum_pass: true,
  cf_checksum_pass: true,
  checksum_notes: [],
};

const statementYear2023: ReclassifiedStatements = {
  period: { year: 2023, quarter: null, label: "FY2023" },
  income_statement: [
    { label: "Revenue", value: "714289000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Cost of sales", value: "-378768000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Gross profit", value: "335521000", is_adjusted: false, adjustment_note: null, source: null },
    { label: "Operating profit", value: "193600000", is_adjusted: true, adjustment_note: "Module B reclassification", source: null },
    { label: "Profit for the year", value: "131000000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  balance_sheet: [
    { label: "Property, plant and equipment", value: "540000000", is_adjusted: false, adjustment_note: null, source: null, category: "non_current_assets" },
    { label: "Total assets", value: "3500000000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  cash_flow: [
    { label: "Net cash from operating activities", value: "180000000", is_adjusted: false, adjustment_note: null, source: null },
  ],
  bs_checksum_pass: true,
  is_checksum_pass: true,
  cf_checksum_pass: true,
  checksum_notes: [],
};

export const canonicalFixture: CanonicalState = {
  extraction_id: "1846-HK_FY2024_2026",
  extraction_date: "2026-04-24T21:16:44Z",
  as_of_date: "2024-12-31",
  identity: identityFixture,
  reclassified_statements: [statementYear2024, statementYear2023],
  adjustments: {
    module_a_taxes: [],
    module_b_provisions: [],
    module_c_leases: [],
    module_d_pensions: [],
    module_d_note_decompositions: {},
    module_d_coverage: null,
    module_e_sbc: [],
    module_f_capitalize: [],
    patches: [],
    decision_log: [],
    estimates_log: [],
  },
  analysis: {
    invested_capital_by_period: [
      {
        period: { year: 2024, quarter: null, label: "FY2024" },
        operating_assets: "2200000000",
        operating_liabilities: "350000000",
        invested_capital: "1850000000",
        financial_assets: "650000000",
        financial_liabilities: "0",
        bank_debt: "0",
        equity_claims: "2500000000",
        nci_claims: "0",
        cross_check_residual: "0",
      },
    ],
    nopat_bridge_by_period: [],
    ratios_by_period: [
      {
        period: { year: 2024, quarter: null, label: "FY2024" },
        roic: "0.072",
        roic_reported: "0.062",
        roic_adj_leases: null,
        roe: "0.034",
        ros: "0.118",
        operating_margin: "0.162",
        sustainable_operating_margin: "0.155",
        ebitda_margin: "0.205",
        net_debt_ebitda: "-3.2",
        capex_revenue: "0.112",
        dso: "30.0",
        dpo: "45.0",
        dio: "20.0",
      },
    ],
    capital_allocation: null,
    dupont_decomposition: null,
    cf_quality_analysis: null,
    unit_economics: null,
  },
  quarterly: null,
  validation: {
    universal_checksums: [],
    profile_specific_checksums: [],
    confidence_rating: "HIGH",
    blocking_issues: [],
  },
  vintage: { vintage_tags: [], cascade_log: [] },
  methodology: {
    extraction_system_version: "1.5.16",
    profile_applied: "P1",
    protocols_activated: [],
    sub_modules_active: {},
    tiers: {},
    llm_calls_summary: {},
    total_api_cost_usd: null,
    audit_status: "audited",
    preliminary_flag: null,
    source_document_type: null,
  },
  narrative_context: null,
  source_documents: [],
};

export const valuationFixture: ValuationSnapshot = {
  version: 1,
  created_at: "2026-04-24T21:16:44Z",
  created_by: "system",
  previous_version: null,
  snapshot_id: "1846-HK_20260424T211644Z",
  ticker: "1846.HK",
  company_name: "EuroEyes International Eye Clinic Limited",
  profile: "P1",
  valuation_date: "2026-04-24",
  based_on_extraction_id: "1846-HK_FY2024_2026",
  based_on_extraction_date: "2026-04-24T21:16:44Z",
  market: {
    price: "2.65",
    price_date: "2026-02-10",
    shares_outstanding: "331885000",
    market_cap: "846680668",
    cost_of_equity: "0.0812",
    wacc: "0.0812",
    currency: "HKD",
  },
  scenarios: [
    {
      label: "base",
      description: "Mid-case",
      probability: "0.32",
      horizon_years: 5,
      drivers: { revenue_growth: "0.08", operating_margin: "0.18" },
      targets: { fair_value_per_share: "8.85", enterprise_value: null, equity_value: null, multiple_at_exit: null },
      irr_3y: "0.27",
      irr_5y: null,
      irr_decomposition: null,
      upside_pct: "234",
      survival_conditions: [],
      kill_signals: [],
      projection: null,
      terminal: null,
      enterprise_value_breakdown: null,
      equity_bridge: {
        enterprise_value: "2900000000",
        net_debt: "-650000000",
        non_operating_assets: "0",
        equity_value: "2937000000",
        shares_outstanding: "331885000",
        fair_value_per_share: "8.85",
      },
      sensitivity_grids: null,
    },
    {
      label: "bull_operational",
      description: "Bull case",
      probability: "0.15",
      horizon_years: 5,
      drivers: { revenue_growth: "0.12" },
      targets: { fair_value_per_share: "12.84", enterprise_value: null, equity_value: null, multiple_at_exit: null },
      irr_3y: "0.45",
      irr_5y: null,
      irr_decomposition: null,
      upside_pct: "384",
      survival_conditions: [],
      kill_signals: [],
      projection: null,
      terminal: null,
      enterprise_value_breakdown: null,
      equity_bridge: null,
      sensitivity_grids: null,
    },
  ],
  weighted: {
    expected_value: "8.63",
    expected_value_method_used: "DCF_FCFF",
    fair_value_range_low: "5.50",
    fair_value_range_high: "10.20",
    upside_pct: "225",
    asymmetry_ratio: "999",
    weighted_irr_3y: "0.27",
    weighted_irr_5y: null,
  },
  reverse: {},
  cross_checks: {},
  eps_bridge: null,
  catalysts: [],
  factor_exposures: null,
  scenario_response: null,
  sensitivities: null,
  conviction: {
    forecast: "medium",
    valuation: "medium",
    asymmetry: "medium",
    timing_risk: "medium",
    liquidity_risk: "medium",
    governance_risk: "medium",
  },
  guardrails: [],
  forecast_system_version: "0.9.5",
  source_documents: [],
  total_api_cost_usd: null,
};

export const fichaFixture: Ficha = {
  version: 1,
  created_at: "2026-04-24T21:16:44Z",
  created_by: "system",
  previous_version: null,
  ticker: "1846.HK",
  identity: identityFixture,
  thesis: "Net-cash compounding M&A platform; market underprices European roll-up.",
  current_extraction_id: "1846-HK_FY2024_2026",
  current_valuation_snapshot_id: "1846-HK_20260424T211644Z",
  position: null,
  conviction: {
    forecast: "medium",
    valuation: "medium",
    asymmetry: "medium",
    timing_risk: "medium",
    liquidity_risk: "medium",
    governance_risk: "medium",
  },
  monitorables: [],
  tags: [],
  market_contexts: [
    {
      market: "HK",
      currency: "HKD",
      share_price: "2.92",
      market_cap: "969182200",
      shares_outstanding: "331885000",
      source: "yfinance",
      as_of_date: "2026-04-24",
    },
  ],
  snapshot_age_days: 0,
  is_stale: false,
  next_earnings_expected: null,
  narrative_summary: null,
};

export const yamlListFixture: YamlListItem[] = [
  {
    name: "scenarios",
    filename: "scenarios.yaml",
    last_modified: "2026-04-23T19:24:00Z",
    size_bytes: 9673,
    versions_count: 2,
  },
  {
    name: "capital_allocation",
    filename: "capital_allocation.yaml",
    last_modified: "2026-04-24T13:06:13Z",
    size_bytes: 8734,
    versions_count: 0,
  },
];
