import type { CanonicalState } from "@/lib/types/canonical";
import type { ValuationSnapshot } from "@/lib/types/valuation";
import { formatPercent } from "@/lib/utils/format";
import { SectionShell, EmptySectionNote } from "./section-shell";

interface Props {
  valuation: ValuationSnapshot;
  canonical: CanonicalState;
}

/**
 * Section 7 — WACC build-up.
 *
 * The PTE valuation snapshot exposes the headline ``cost_of_equity`` and
 * ``wacc`` on ``valuation.market``. The richer geographic-mix breakdown
 * lives in the WACC inputs file rather than the snapshot today; we
 * surface what's available and link the analyst to ``pte analyze`` for
 * the full Sprint-3 build-up.
 */
export function WaccBuildup({ valuation, canonical }: Props) {
  const market = valuation.market;
  const currency = market.currency || canonical.identity.reporting_currency;

  return (
    <SectionShell
      title="WACC Build-up"
      subtitle="Weighted average cost of capital derivation"
    >
      <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
        <div className="rounded-md border border-border p-4">
          <h3 className="mb-3 font-mono text-xs font-semibold uppercase text-muted-foreground">
            Headline rates
          </h3>
          <div className="space-y-2 text-sm">
            <Row label="Cost of equity" value={formatPercent(market.cost_of_equity)} />
            <Row label="WACC" value={formatPercent(market.wacc)} emphasize />
          </div>
          <p className="mt-3 text-xs text-muted-foreground">
            Reporting currency: {currency}. Pulled from the latest valuation
            snapshot (
            <span className="font-mono">{valuation.based_on_extraction_id}</span>
            ).
          </p>
        </div>

        <div className="rounded-md border border-dashed border-border p-4">
          <h3 className="mb-3 font-mono text-xs font-semibold uppercase text-muted-foreground">
            Build-up components
          </h3>
          <EmptySectionNote message="Geographic CRP / risk-free / ERP / β breakdown is generated by `pte analyze` and lives in WACC inputs. Sprint 1B will surface that table here." />
        </div>
      </div>
    </SectionShell>
  );
}

function Row({
  label,
  value,
  emphasize = false,
}: {
  label: string;
  value: string;
  emphasize?: boolean;
}) {
  return (
    <div
      className={`flex items-baseline justify-between ${emphasize ? "font-semibold" : ""}`}
    >
      <span className="text-muted-foreground">{label}</span>
      <span className="font-mono tabular-nums">{value}</span>
    </div>
  );
}
